services:
    dev-api:
        extends:
            file: docker/development/docker-compose.yml
            service: dev-api
        networks:
            - neural-msg-dev
        depends_on:
            - dev-mongo

    dev-mongo:
        extends:
            file: docker/development/docker-compose.yml
            service: dev-mongo
        networks:
            - neural-msg-dev
        volumes:
            - mongodb_data:/data/db

networks:
    neural-msg-dev:
        driver: bridge

volumes:
    mongodb_data:
        driver: local
    node_modules:
        driver: local
